name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          echo "Setting up Node.js version"
          node -v

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - run: |
          echo "jaime1 pwd"
          pwd
          echo "jaime1 ls"
          ls
          cd tms-next-abp
          npm install turbo -g
          npm install -g pnpm
          pnpm i
          pnpm turbo run build
          echo "jaime pwd"
          pwd
          cp -r apps/abp/.next/standalone/apps/abp/. apps/abp/.next/standalone

      # - name: Pre-deployment Log
      #   run: |
      #     echo "Starting deployment to Azure Static Web Apps"
      #     echo "Application location: tms-next-abp/apps/abp"
      #     cd tms-next-abp/apps/abp/.next/standalone
      #     ls
      #     if [ -d "node_modules" ]; then
      #     echo "node_modules folder exists"
      #     ls -la node_modules
      #     else
      #       echo "node_modules folder does not exist"
      #     fi

      - name: Validate staticwebapp.config.json
        run: |
          echo "Validating staticwebapp.config.json"
          echo "current location"
          cd tms-next-abp
          pwd
          ls
          if [ -f "staticwebapp.config.json" ]; then
            echo "staticwebapp.config.json found:"
            cat staticwebapp.config.json
          else
            echo "staticwebapp.config.json not found!"
          fi

      - name: Verify node_modules in standalone
        run: |
          echo "Verifying node_modules in .next/standalone"
          cd tms-next-abp/apps/abp/.next/standalone
          if [ ! -d "node_modules" ]; then
            echo "node_modules not found, installing dependencies"
            pnpm install --prod
          else
            echo "node_modules exists"
          fi
          ls -la node_modules

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CF08C00F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "tms-next-abp/apps/abp"
          api_location: ""
      # - name: Build And Deploy1
      #   id: builddeploy1
      #   uses: Azure/static-web-apps-deploy@v1
      #   env:
      #     PRE_BUILD_COMMAND: npm install -g pnpm && pnpm install
      #     # CUSTOM_BUILD_COMMAND: pnpm turbo run build
      #     CUSTOM_BUILD_COMMAND: pnpm turbo run build && cp -r apps/abp/.next/standalone/apps/abp/. apps/abp/.next/standalone
      #     VERBOSE: true
      #     # API_UPLOAD_ENDPOINT: ${{ secrets.API_UPLOAD_ENDPOINT}}
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CF08C00F }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "tms-next-abp" # App source code path
      #     api_location: "" # Api source code path - optional
      #     output_location: "apps/abp/.next/standalone/apps/abp/" # Built app content directory - optional
      #     ###### End of Repository/Build Configurations ######

      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   env:
      #     PRE_BUILD_COMMAND: npm install -g pnpm && pnpm install
      #     CUSTOM_BUILD_COMMAND: pnpm run build && cp -r .next/standalone/tms-next-abp/apps/abp/. .next/standalone
      #     VERBOSE: true
      #     # API_UPLOAD_ENDPOINT: ${{ secrets.API_UPLOAD_ENDPOINT}}
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CF08C00F }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "tms-next-abp/apps/abp" # App source code path
      #     api_location: "" # Api source code path - optional
      #     output_location: "" # Built app content directory - optional
      #     ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CF08C00F }}
          action: "close"
